seo optimisation
1alexvash/AlexCodeBlog pull request #17
Opened 2022-09-29 08:56 UTC by ntorbinskiy

seo optimisation of AlexCode

2022-10-02 07:12 UTC, 1alexvash requested changes
Waiting for the update in this pull request

2022-10-02 07:27 UTC, 1alexvash commented on components/Post/PostContent.tsx
> +//привет
``
```suggestion
```

2022-10-02 09:43 UTC, ntorbinskiy commented on components/Post/PostContent.tsx
> +        <meta name="description" content={config.site_description} />
Okey, Which description would you like to see?

2022-10-02 09:49 UTC, ntorbinskiy commented on pages/index.tsx
>          <meta property="og:title" content={config.site_keywords[1]} />
Are you talking about "og:title", am I right?

2022-10-02 09:54 UTC, ntorbinskiy commented on pages/index.tsx
> +        <meta name="description" content={config.site_description} />
Prettier automatically deletes break line after meta tags. I turned off ,,Format on Save'' to save this break line

2022-10-05 19:39 UTC, 1alexvash commented on pages/index.tsx
>          <meta property="og:title" content={config.site_keywords[1]} />
@ntorbinskiy 
Yeah, as it is a comment under line 42

2022-10-05 19:43 UTC, 1alexvash commented on pages/index.tsx
> +        <meta name="description" content={config.site_description} />
@ntorbinskiy 
![Animation](https://user-images.githubusercontent.com/46556479/194148474-36c00a80-c233-40b9-a45b-26266a025336.gif)
What do you mean by saying prettier deletes break lines?
It works for me perfectly

2022-10-06 11:32 UTC, ntorbinskiy commented on pages/index.tsx
> +        <meta name="description" content={config.site_description} />
https://www.loom.com/share/98f6cd909221480499e0424aab17ea52

2022-10-06 12:00 UTC, ntorbinskiy commented on pages/index.tsx
>          <meta property="og:title" content={config.site_keywords[1]} />
### Main Ideas

1. Keep OG title short (without a brand name) with 60 characters for desktop and 40 for mobile.
2. Title Tags Should Contain Your Main Keyword
3. For best results, try to put your focus keyword as close to the beginning of your title as possible. That’s so search engines (and people) will see the keyword early on.
4. Make sure the keyword placement is organic. It’s preferable that the keyword is close to the beginning, but it’s not necessary for great SEO.
5. Much like a headline, a title tag needs to communicate a benefit to stand out.
6. Google suggests using your homepage title tag to include the most branding.
7.For most of your pages, adding your brand to the end of the title tag will suffice
8.Avoid Duplicate Title Tags

**Conclusion:**

### How do you write a good title tag?
Pay attention to the length, use the main keyword the page targets, and explain what benefit the user will get by clicking.

### How long should title tags be?
Between 50 and 50 characters. Any longer than that and Google may truncate your title.

### How many keywords should be in my title tags?
Generally just one. You can add a second if it is closely related and makes sense. Don’t keyword stuff; the goal of the title tag is to explain what users can expect

2022-10-06 12:02 UTC, ntorbinskiy commented on pages/index.tsx
>          <meta property="og:title" content={config.site_keywords[1]} />
https://neilpatel.com/blog/open-graph-meta-tags/
https://neilpatel.com/blog/title-tags-seo/
https://magefan.com/blog/open-graph-meta-tags

2022-10-06 19:23 UTC, 1alexvash commented on pages/index.tsx
> +        <meta name="description" content={config.site_description} />
@ntorbinskiy Um, funny

Do we have the same formatting settings, and user the same formatter?

https://i.stack.imgur.com/XohQa.png

2022-10-07 06:45 UTC, 1alexvash commented on components/Post/PostContent.tsx
> +          height={300}
```suggestion
          height={394}
```

2022-10-07 06:48 UTC, 1alexvash commented on components/Post/PostContent.tsx
> +        <meta name="description" content={config.site_description} />
@ntorbinskiy Nothing, sorry, this one is fine, I thought you did edit the page description

2022-10-07 06:49 UTC, 1alexvash commented on pages/index.tsx
> +        <meta name="description" content={config.site_description} />
@ntorbinskiy What's the difference between line 42 and 47?

2022-10-08 09:36 UTC, ntorbinskiy commented on pages/index.tsx
> +        <meta name="description" content={config.site_description} />
Yes, we do

2022-10-09 06:28 UTC, closed without merging